{
 "title": "CCX Upgrade Risks Predictions",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (up{service=\"ccx-upgrades-data-eng-svc\", namespace=\"$namespace\"})",
     "legendFormat": "Data-Eng"
    },
    {
     "expr": "sum (up{service=\"ccx-upgrades-inference-svc\", namespace=\"$namespace\"})",
     "legendFormat": "Inference"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"ccx-upgrades-data-eng-instance\"}[1m]))",
     "legendFormat": "Data Engineering"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"ccx-upgrades-inference-instance\"}[1m]))",
     "legendFormat": "Inference"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\",container=\"ccx-upgrades-data-eng-instance\"})",
     "legendFormat": "Data Engineering"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\",container=\"ccx-upgrades-inference-instance\"})",
     "legendFormat": "Inference"
    }
   ]
  },
  {
   "title": "Requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\", service=\"ccx-upgrades-data-eng-svc\"}[1m])) by (handler)",
     "legendFormat": "data-eng: {{ handler }}"
    },
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\", service=\"ccx-upgrades-inference-svc\"}[1m])) by (handler)",
     "legendFormat": "inference: {{ handler }}"
    }
   ]
  },
  {
   "title": "Request size by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_sum{namespace=\"$namespace\", service=\"ccx-upgrades-data-eng-svc\"}[1m])) by (handler)\n/\nsum(rate(http_request_size_bytes_count{namespace=\"$namespace\", service=\"ccx-upgrades-data-eng-svc\"}[1m])) by (handler)",
     "legendFormat": "data-eng: {{ handler }}"
    },
    {
     "expr": "sum(rate(http_request_size_bytes_sum{namespace=\"$namespace\", service=\"ccx-upgrades-inference-svc\"}[1m])) by (handler)\n/\nsum(rate(http_request_size_bytes_count{namespace=\"$namespace\", service=\"ccx-upgrades-inference-svc\"}[1m])) by (handler)",
     "legendFormat": "inference: {{ handler }}"
    }
   ]
  },
  {
   "title": "Response size by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_response_size_bytes_sum{namespace=\"$namespace\", service=\"ccx-upgrades-data-eng-svc\"}[1m])) by (handler)\n/\nsum(rate(http_response_size_bytes_count{namespace=\"$namespace\", service=\"ccx-upgrades-data-eng-svc\"}[1m])) by (handler)",
     "legendFormat": "data-eng: {{ handler }}"
    },
    {
     "expr": "sum(rate(http_response_size_bytes_sum{namespace=\"$namespace\", service=\"ccx-upgrades-inference-svc\"}[1m])) by (handler)\n/\nsum(rate(http_response_size_bytes_count{namespace=\"$namespace\", service=\"ccx-upgrades-inference-svc\"}[1m])) by (handler)",
     "legendFormat": "inference: {{ handler }}"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(increase(http_requests_total{namespace=\"$namespace\", service=\"ccx-upgrades-data-eng-svc\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "data-eng: {{ status }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by(status)(increase(http_requests_total{namespace=\"$namespace\", service=\"ccx-upgrades-inference-svc\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inference: {{ status }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by(handler)(rate(http_request_duration_seconds_sum{namespace=\"$namespace\", service=\"ccx-upgrades-data-eng-svc\"}[5m]) / rate(http_request_duration_seconds_count{namespace=\"$namespace\", service=\"ccx-upgrades-data-eng-svc\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "data-eng: {{handler}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg by(handler)(rate(http_request_duration_seconds_sum{namespace=\"$namespace\", service=\"ccx-upgrades-inference-svc\"}[5m]) / rate(http_request_duration_seconds_count{namespace=\"$namespace\", service=\"ccx-upgrades-inference-svc\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inference: {{handler}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}